#!/usr/bin/env python3
"""Update the HIP index and the reading order in README.md from the HIP files.

TWO PROJECTIONS OF ONE CORPUS, neither hand-maintained.

The index is every HIP by number, which is what you want when you already know
the number. The reading order is what you want when you do not: 251 specs in
numeric order teach nothing, because number records when a spec was written and
not what has to be understood first.

The order is DERIVED, never curated. A HIP's `requires:` names what a reader must
already hold, so counting how many HIPs require a given one measures how
foundational the corpus itself treats it -- and the answer is sharp rather than a
judgement call: three HIPs are required by more than a hundred others and the
fourth is required by twenty-three. Capability HIPs then group by the domain
`capabilities.yaml` files them under, which is the same grouping the doc site and
the sidebar use.

Deriving it means it cannot drift. A HIP that becomes foundational rises without
anyone noticing it should, and one that stops being required falls.
"""
import os
import re
from pathlib import Path

try:
    import yaml
except ImportError:  # the reading order degrades, the index does not
    yaml = None

# Where the domain grouping lives. It is hanzoai/openapi's editorial decision and
# this script reads it rather than restating it -- a second copy of a taxonomy is
# a second answer the day one of them moves.
CAPABILITIES = Path(__file__).parent.parent.parent / 'openapi' / 'capabilities.yaml'

# How many HIPs must require one for it to lead the reading order. Set from the
# measured distribution, which has a wide gap in it: 104, 102, 102, then 23. Any
# threshold between 24 and 102 selects the same three, so the number is not a
# knob anybody has to tune.
FOUNDATION = 40

def extract_frontmatter(filepath):
    """Extract YAML frontmatter from a markdown file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    if not content.startswith('---'):
        return {}
    end = content.find('\n---', 3)
    if end == -1:
        return {}
    fm_text = content[3:end].strip()
    data = {}
    for line in fm_text.splitlines():
        if ':' in line:
            key, val = line.split(':', 1)
            data[key.strip()] = val.strip().strip('"').strip("'")
    return data

def get_all_hips(directory='HIPs'):
    """Get all HIP files and their metadata."""
    hips = []
    for filename in os.listdir(directory):
        if filename.endswith('.md') and filename.startswith('hip-'):
            filepath = os.path.join(directory, filename)
            fm = extract_frontmatter(filepath)
            match = re.search(r'hip-(\d+)(?:-[a-z0-9-]+)?\.md', filename)
            if match:
                number = int(match.group(1))
                fm['number'] = number
                fm['filename'] = filename
                hips.append(fm)
    hips.sort(key=lambda x: x['number'])
    return hips

def generate_index_table(hips):
    """Generate markdown table for HIPs."""
    lines = [
        "## HIP Index\n",
        "| Number | Title | Type | Category | Status |",
        "|:-------|:------|:-----|:---------|:-------|"
    ]
    for h in hips:
        num = h['number']
        filename = h.get('filename', f'hip-{num:04d}.md')
        title = h.get('title', 'Untitled')
        htype = h.get('type', '-')
        category = h.get('category', '-') or '-'
        status = h.get('status', 'Draft')
        if len(title) > 55:
            title = title[:52] + '...'
        lines.append(f"| [HIP-{num:04d}](./HIPs/{filename}) | {title} | {htype} | {category} | {status} |")
    return '\n'.join(lines)

def requires_count(hips):
    """How many HIPs name each one in `requires:`."""
    counts = {}
    for h in hips:
        for m in re.finditer(r'HIP-(\d{4})', h.get('requires', '') or ''):
            n = int(m.group(1))
            counts[n] = counts.get(n, 0) + 1
    return counts


def domains():
    """The domain grouping, from capabilities.yaml. Empty if it cannot be read."""
    if yaml is None or not CAPABILITIES.exists():
        return []
    try:
        with open(CAPABILITIES, encoding='utf-8') as f:
            return yaml.safe_load(f).get('domains') or []
    except Exception:
        return []


def generate_reading_order(hips):
    """The corpus in the order it is learnable, derived from `requires:`."""
    counts = requires_count(hips)
    by_number = {h['number']: h for h in hips}
    link = lambda h: f"[HIP-{h['number']:04d}](./HIPs/{h['filename']})"

    lines = ['## Reading order\n']
    lines.append(
        'Every HIP by number is indexed below. This is the order it is learnable in, '
        'derived from the corpus rather than curated: a HIP\'s `requires:` names what a '
        'reader must already hold, so what the most HIPs require is what to read first. '
        'Regenerated by `scripts/update-index.py`.\n'
    )

    lines.append('### Start here\n')
    lines.append('| | Required by | |')
    lines.append('|:--|--:|:--|')
    zero = by_number.get(0)
    if zero:
        lines.append(f"| {link(zero)} | — | {zero.get('title', '')} — the map |")
    foundation = sorted(
        (n for n, c in counts.items() if c >= FOUNDATION and n in by_number),
        key=lambda n: -counts[n],
    )
    for n in foundation:
        h = by_number[n]
        lines.append(f"| {link(h)} | {counts[n]} | {h.get('title', '')} |")
    lines.append('')

    # The next tier: required by enough HIPs to be worth holding before the
    # capabilities, but not by nearly all of them.
    second = sorted(
        (n for n, c in counts.items() if 5 <= c < FOUNDATION and n in by_number),
        key=lambda n: -counts[n],
    )
    if second:
        lines.append('### Then the invariants\n')
        lines.append('| | Required by | |')
        lines.append('|:--|--:|:--|')
        for n in second:
            h = by_number[n]
            lines.append(f"| {link(h)} | {counts[n]} | {h.get('title', '')} |")
        lines.append('')

    # Capability HIPs, grouped the way the doc site groups them.
    with_cap = {}
    for h in hips:
        cap = (h.get('capability') or '').strip().strip('[]')
        if cap and ',' not in cap:
            with_cap.setdefault(cap, h)
    ds = domains()
    if with_cap and ds:
        lines.append('### The capabilities\n')
        lines.append(
            f'One capability, one HIP (HIP-0139). {len(with_cap)} of them, grouped as '
            '`capabilities.yaml` groups them.\n'
        )
        filed = set()
        for d in ds:
            rows = [with_cap[t] for t in (d.get('tags') or []) if t in with_cap]
            if not rows:
                continue
            filed.update(r['number'] for r in rows)
            lines.append(f"**{d.get('title', d.get('id', ''))}** — {d.get('role', '')}\n")
            lines.append(
                ' · '.join(
                    f"{link(h)} `{(h.get('capability') or '').strip()}`"
                    for h in sorted(rows, key=lambda x: x['number'])
                )
            )
            lines.append('')
        rest = [h for h in with_cap.values() if h['number'] not in filed]
        if rest:
            lines.append('**Not yet grouped**\n')
            lines.append(
                ' · '.join(
                    f"{link(h)} `{(h.get('capability') or '').strip()}`"
                    for h in sorted(rest, key=lambda x: x['number'])
                )
            )
            lines.append('')

    return '\n'.join(lines)


def replace_section(content, marker, new):
    """Swap one `## Section` for new text, or append it if absent."""
    start = content.find(marker)
    if start == -1:
        return content.rstrip() + '\n\n' + new + '\n'
    nxt = re.search(r'\n## [^#]', content[start + len(marker):])
    if not nxt:
        return content[:start] + new
    end = start + len(marker) + nxt.start()
    return content[:start] + new + '\n\n' + content[end + 1:]


def update_readme():
    """Update README.md with new index."""
    readme_path = 'README.md'
    with open(readme_path, 'r', encoding='utf-8') as f:
        content = f.read()

    hips = get_all_hips()
    content = replace_section(content, '## Reading order', generate_reading_order(hips))
    content = replace_section(content, '## HIP Index', generate_index_table(hips))

    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(content)

    caps = sum(1 for h in hips if (h.get('capability') or '').strip())
    print(f"Updated README.md: {len(hips)} HIPs indexed, {caps} capabilities in the reading order")

if __name__ == '__main__':
    os.chdir(Path(__file__).parent.parent)
    update_readme()
